name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CCACHE_DIR: '${{ github.workspace }}/.ccache'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.type }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        type: ['Release', 'Debug']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    steps:
    - name: Setup MinGw
      if: runner.os == 'Windows'
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Setup x11 development environment for linux
      if: runner.os == 'Linux'
      run: sudo apt-get install -y xorg-dev

    - name: Checkout from git
      uses: actions/checkout@v2
      with:
        submodules: true
      
    - name: Setup ccache
      uses: chirag-droid/setup-ccache@v0.0.1
      with:
        key: ${{ matrix.type }}-${{ matrix.os }}-ccache

    - name: Build with cmake
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-DCMAKE_BUILD_TYPE=${{ matrix.type }} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache'
        buildWithCMake: true
        buildDirectory: '${{ github.workspace }}/build'
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.type }}
        path: ${{ github.workspace }}/build
